image: node:latest

stages:
  - build
  - lint

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

build:
  stage: build
  script:
    - npm run build

lint:
  stage: lint
  script:
    - npm run lint
