image: trion/ng-cli

stages:
  - build
  - lint

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build

lint:
  stage: lint
  script:
    - npm run lint
